// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJnR9MY-4Rz2qYzJmh9p8pO8w4ytT69z4',
    appId: '1:312140727021:web:8c6dd8d173deed4f38c2e4',
    messagingSenderId: '312140727021',
    projectId: 'kana-colombo-test',
    authDomain: 'kana-colombo-test.firebaseapp.com',
    storageBucket: 'kana-colombo-test.firebasestorage.app',
    measurementId: 'G-P8ZMRHRR9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlIJKjNMkYfIVq7_WXmf2JYuSK9osYet0',
    appId: '1:312140727021:android:df92e01340da661638c2e4',
    messagingSenderId: '312140727021',
    projectId: 'kana-colombo-test',
    storageBucket: 'kana-colombo-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-z3YZ3CDNeGoWMfBN1tu8UgTQrVQtJPo',
    appId: '1:312140727021:ios:23784542ae4933bf38c2e4',
    messagingSenderId: '312140727021',
    projectId: 'kana-colombo-test',
    storageBucket: 'kana-colombo-test.firebasestorage.app',
    iosBundleId: 'com.codebridge.apps.kanacolombotest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-z3YZ3CDNeGoWMfBN1tu8UgTQrVQtJPo',
    appId: '1:312140727021:ios:92c4fbc1a0486e6338c2e4',
    messagingSenderId: '312140727021',
    projectId: 'kana-colombo-test',
    storageBucket: 'kana-colombo-test.firebasestorage.app',
    iosBundleId: 'com.cb.project.template.codebridgeFlutterAllInOnePlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJnR9MY-4Rz2qYzJmh9p8pO8w4ytT69z4',
    appId: '1:312140727021:web:e9846f3c3399229638c2e4',
    messagingSenderId: '312140727021',
    projectId: 'kana-colombo-test',
    authDomain: 'kana-colombo-test.firebaseapp.com',
    storageBucket: 'kana-colombo-test.firebasestorage.app',
    measurementId: 'G-HP7M5JRW9B',
  );
}
